[tool.poetry]
name = "fdh"
version = "0.0.0"
description = "File date helpers"

[tool.poetry.dependencies]
python = ">=3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
